/***************************************************************************/
/* Copyright(C) 2020

 Marco Livesu
 Italian National Research Council

 and

 Nico Pietroni
 University Of Technology Sydney

 All rights reserved.
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
****************************************************************************/

#ifndef FINALIZATION_H
#define FINALIZATION_H

#include "state.h"

// - adds cuts that fix valence 2 verts
// - remove cuts that generated non fixable valence 2 verts
// - removes valence 4 verts that may be generated by the previous two steps
void finalize_block_decomposition(GlobalState & state);

#endif // FINALIZATION_H
