#ifndef FINALIZATION_H
#define FINALIZATION_H

#include "state.h"

// - adds cuts that fix valence 2 verts
// - remove cuts that generated non fixable valence 2 verts
// - removes valence 4 verts that may be generated by the previous two steps
void finalize_block_decomposition(GlobalState & state);

#endif // FINALIZATION_H
